<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_label</name>
   <tag></tag>
   <elementGuidId>a0dee49e-b943-4143-a03e-70f723404bd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='product_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='product_label']</value>
      <webElementGuid>2c0094a7-570a-466a-aacc-c38d244e3a4a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
